.class public final Lcom/google/android/gms/internal/zzqq;
.super Lcom/google/android/gms/common/api/OptionalPendingResult;
.source "dalvik_source_tower-dev-debug.400010.apk"


# annotations
.annotation system Ldalvik/annotation/Signature;
    value = {
        "<R::",
        "Lcom/google/android/gms/common/api/Result;",
        ">",
        "Lcom/google/android/gms/common/api/OptionalPendingResult",
        "<TR;>;"
    }
.end annotation


# instance fields
.field private final vu:Lcom/google/android/gms/internal/zzpo;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Lcom/google/android/gms/internal/zzpo",
            "<TR;>;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>(Lcom/google/android/gms/common/api/PendingResult;)V
    .registers 7
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lcom/google/android/gms/common/api/PendingResult",
            "<TR;>;)V"
        }
    .end annotation

    invoke-direct {p0}, Lcom/google/android/gms/common/api/OptionalPendingResult;-><init>()V

    instance-of v0, p1, Lcom/google/android/gms/internal/zzpo;

    .local v0, "$z0":Z, ""
    if-nez v0, :cond_f

    new-instance v1, Ljava/lang/IllegalArgumentException;

    .local v1, "$r2":Ljava/lang/IllegalArgumentException;, ""
    const-string v2, "OptionalPendingResult can only wrap PendingResults generated by an API call."

    invoke-direct {v1, v2}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v1

    :cond_f
    move-object v4, p1

    check-cast v4, Lcom/google/android/gms/internal/zzpo;

    move-object v3, v4

    .local v3, "$r3":Lcom/google/android/gms/internal/zzpo;, ""
    iput-object v3, p0, Lcom/google/android/gms/internal/zzqq;->vu:Lcom/google/android/gms/internal/zzpo;

    return-void
    .end local v1    # "$r2":Ljava/lang/IllegalArgumentException;, ""
    .end local v3    # "$r3":Lcom/google/android/gms/internal/zzpo;, ""
    .end local v0    # "$z0":Z, ""
.end method


# virtual methods
.method public await()Lcom/google/android/gms/common/api/Result;
    .registers 3
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()TR;"
        }
    .end annotation

    iget-object v0, p0, Lcom/google/android/gms/internal/zzqq;->vu:Lcom/google/android/gms/internal/zzpo;

    .local v0, "$r2":Lcom/google/android/gms/internal/zzpo;, ""
    invoke-virtual {v0}, Lcom/google/android/gms/internal/zzpo;->await()Lcom/google/android/gms/common/api/Result;

    move-result-object v1

    .local v1, "$r1":Lcom/google/android/gms/common/api/Result;, ""
    return-object v1
    .end local v1    # "$r1":Lcom/google/android/gms/common/api/Result;, ""
    .end local v0    # "$r2":Lcom/google/android/gms/internal/zzpo;, ""
.end method

.method public await(JLjava/util/concurrent/TimeUnit;)Lcom/google/android/gms/common/api/Result;
    .registers 6
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(J",
            "Ljava/util/concurrent/TimeUnit;",
            ")TR;"
        }
    .end annotation

    iget-object v0, p0, Lcom/google/android/gms/internal/zzqq;->vu:Lcom/google/android/gms/internal/zzpo;

    .local v0, "$r3":Lcom/google/android/gms/internal/zzpo;, ""
    invoke-virtual {v0, p1, p2, p3}, Lcom/google/android/gms/internal/zzpo;->await(JLjava/util/concurrent/TimeUnit;)Lcom/google/android/gms/common/api/Result;

    move-result-object v1

    .local v1, "$r2":Lcom/google/android/gms/common/api/Result;, ""
    return-object v1
    .end local v0    # "$r3":Lcom/google/android/gms/internal/zzpo;, ""
    .end local v1    # "$r2":Lcom/google/android/gms/common/api/Result;, ""
.end method

.method public cancel()V
    .registers 2

    iget-object v0, p0, Lcom/google/android/gms/internal/zzqq;->vu:Lcom/google/android/gms/internal/zzpo;

    .local v0, "$r1":Lcom/google/android/gms/internal/zzpo;, ""
    invoke-virtual {v0}, Lcom/google/android/gms/internal/zzpo;->cancel()V

    return-void
    .end local v0    # "$r1":Lcom/google/android/gms/internal/zzpo;, ""
.end method

.method public get()Lcom/google/android/gms/common/api/Result;
    .registers 8
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()TR;"
        }
    .end annotation

    invoke-virtual {p0}, Lcom/google/android/gms/internal/zzqq;->isDone()Z

    move-result v0

    .local v0, "$z0":Z, ""
    if-eqz v0, :cond_f

    sget-object v1, Ljava/util/concurrent/TimeUnit;->MILLISECONDS:Ljava/util/concurrent/TimeUnit;

    .local v1, "$r1":Ljava/util/concurrent/TimeUnit;, ""
    const-wide/16 v3, 0x0

    invoke-virtual {p0, v3, v4, v1}, Lcom/google/android/gms/internal/zzqq;->await(JLjava/util/concurrent/TimeUnit;)Lcom/google/android/gms/common/api/Result;

    move-result-object v2

    .local v2, "$r2":Lcom/google/android/gms/common/api/Result;, ""
    return-object v2

    :cond_f
    new-instance v5, Ljava/lang/IllegalStateException;

    .local v5, "$r3":Ljava/lang/IllegalStateException;, ""
    const-string v6, "Result is not available. Check that isDone() returns true before calling get()."

    invoke-direct {v5, v6}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v5
    .end local v0    # "$z0":Z, ""
    .end local v2    # "$r2":Lcom/google/android/gms/common/api/Result;, ""
    .end local v1    # "$r1":Ljava/util/concurrent/TimeUnit;, ""
    .end local v5    # "$r3":Ljava/lang/IllegalStateException;, ""
.end method

.method public isCanceled()Z
    .registers 3

    iget-object v0, p0, Lcom/google/android/gms/internal/zzqq;->vu:Lcom/google/android/gms/internal/zzpo;

    .local v0, "$r1":Lcom/google/android/gms/internal/zzpo;, ""
    invoke-virtual {v0}, Lcom/google/android/gms/internal/zzpo;->isCanceled()Z

    move-result v1

    .local v1, "$z0":Z, ""
    return v1
    .end local v1    # "$z0":Z, ""
    .end local v0    # "$r1":Lcom/google/android/gms/internal/zzpo;, ""
.end method

.method public isDone()Z
    .registers 3

    iget-object v0, p0, Lcom/google/android/gms/internal/zzqq;->vu:Lcom/google/android/gms/internal/zzpo;

    .local v0, "$r1":Lcom/google/android/gms/internal/zzpo;, ""
    invoke-virtual {v0}, Lcom/google/android/gms/internal/zzpo;->isReady()Z

    move-result v1

    .local v1, "$z0":Z, ""
    return v1
    .end local v0    # "$r1":Lcom/google/android/gms/internal/zzpo;, ""
    .end local v1    # "$z0":Z, ""
.end method

.method public setResultCallback(Lcom/google/android/gms/common/api/ResultCallback;)V
    .registers 3
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lcom/google/android/gms/common/api/ResultCallback",
            "<-TR;>;)V"
        }
    .end annotation

    iget-object v0, p0, Lcom/google/android/gms/internal/zzqq;->vu:Lcom/google/android/gms/internal/zzpo;

    .local v0, "$r2":Lcom/google/android/gms/internal/zzpo;, ""
    invoke-virtual {v0, p1}, Lcom/google/android/gms/internal/zzpo;->setResultCallback(Lcom/google/android/gms/common/api/ResultCallback;)V

    return-void
    .end local v0    # "$r2":Lcom/google/android/gms/internal/zzpo;, ""
.end method

.method public setResultCallback(Lcom/google/android/gms/common/api/ResultCallback;JLjava/util/concurrent/TimeUnit;)V
    .registers 6
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lcom/google/android/gms/common/api/ResultCallback",
            "<-TR;>;J",
            "Ljava/util/concurrent/TimeUnit;",
            ")V"
        }
    .end annotation

    iget-object v0, p0, Lcom/google/android/gms/internal/zzqq;->vu:Lcom/google/android/gms/internal/zzpo;

    .local v0, "$r3":Lcom/google/android/gms/internal/zzpo;, ""
    invoke-virtual {v0, p1, p2, p3, p4}, Lcom/google/android/gms/internal/zzpo;->setResultCallback(Lcom/google/android/gms/common/api/ResultCallback;JLjava/util/concurrent/TimeUnit;)V

    return-void
    .end local v0    # "$r3":Lcom/google/android/gms/internal/zzpo;, ""
.end method

.method public then(Lcom/google/android/gms/common/api/ResultTransform;)Lcom/google/android/gms/common/api/TransformedResult;
    .registers 4
    .param p1    # Lcom/google/android/gms/common/api/ResultTransform;
        .annotation runtime Landroid/support/annotation/NonNull;
        .end annotation
    .end param
    .annotation build Landroid/support/annotation/NonNull;
    .end annotation

    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<S::",
            "Lcom/google/android/gms/common/api/Result;",
            ">(",
            "Lcom/google/android/gms/common/api/ResultTransform",
            "<-TR;+TS;>;)",
            "Lcom/google/android/gms/common/api/TransformedResult",
            "<TS;>;"
        }
    .end annotation

    iget-object v0, p0, Lcom/google/android/gms/internal/zzqq;->vu:Lcom/google/android/gms/internal/zzpo;

    .local v0, "$r3":Lcom/google/android/gms/internal/zzpo;, ""
    invoke-virtual {v0, p1}, Lcom/google/android/gms/internal/zzpo;->then(Lcom/google/android/gms/common/api/ResultTransform;)Lcom/google/android/gms/common/api/TransformedResult;

    move-result-object v1

    .local v1, "$r2":Lcom/google/android/gms/common/api/TransformedResult;, ""
    return-object v1
    .end local v0    # "$r3":Lcom/google/android/gms/internal/zzpo;, ""
    .end local v1    # "$r2":Lcom/google/android/gms/common/api/TransformedResult;, ""
.end method

.method public zza(Lcom/google/android/gms/common/api/PendingResult$zza;)V
    .registers 3

    iget-object v0, p0, Lcom/google/android/gms/internal/zzqq;->vu:Lcom/google/android/gms/internal/zzpo;

    .local v0, "$r2":Lcom/google/android/gms/internal/zzpo;, ""
    invoke-virtual {v0, p1}, Lcom/google/android/gms/internal/zzpo;->zza(Lcom/google/android/gms/common/api/PendingResult$zza;)V

    return-void
    .end local v0    # "$r2":Lcom/google/android/gms/internal/zzpo;, ""
.end method

.method public zzaoj()Ljava/lang/Integer;
    .registers 3

    iget-object v0, p0, Lcom/google/android/gms/internal/zzqq;->vu:Lcom/google/android/gms/internal/zzpo;

    .local v0, "$r2":Lcom/google/android/gms/internal/zzpo;, ""
    invoke-virtual {v0}, Lcom/google/android/gms/internal/zzpo;->zzaoj()Ljava/lang/Integer;

    move-result-object v1

    .local v1, "$r1":Ljava/lang/Integer;, ""
    return-object v1
    .end local v0    # "$r2":Lcom/google/android/gms/internal/zzpo;, ""
    .end local v1    # "$r1":Ljava/lang/Integer;, ""
.end method
